### PR TITLE
feat: inputs with text and input with validation

### PR DESCRIPTION
**Pull request by amarphule**
Created Input fields with
1. Input text box
2. Form with validation
text
text-valid

### CODE REVIEW

**Review by Kavita539 — APPROVED** [review]

**Review by vijaytembugade — APPROVED** [review]
Looks good amardeep. Nice work

**Review by saurabhchirde — APPROVED** [review]
Everything looks good, you can merge it.

**Comment by horsemaker** [comment]
Here, the password field should be of type password, right?
image

**Comment by horsemaker** [comment]
Also, if you could make the sidebar functioning. 👀
It takes a lot to scroll. 😢

**Comment by amarphule** [comment]
> Also, if you could make the sidebar functioning. eyes It takes a lot to scroll. cry

yes sure. I'll do that

**Pull request merged**
